apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: golang-app-monitor
  namespace: golang-app
  labels:
    app: golang-app
    release: prometheus
spec:
  selector:
    matchLabels:
      app: golang-app
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
